# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1b25198578dda780739f2438402a15c2b6ac6f2ab50a7e79d380a898010f620bc9e146bc31eefef6fca17c829dbcea6323534ce08d74d9471e64f56df5f7a95

test:
  secret_key_base: c65c3a3cb0f6dee1e7872ab76404cb6dce58421e9518f4b7919b06d2487fe19dd845664180d58ad430cd18a9a058385bac2dbf57f887c87b5471a18639b8fee0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
